# Generated by Django 4.0.4 on 2022-06-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='../media/users/default-user-avatar.png', upload_to=''),
        ),
    ]
